### ISSUE TITLE
Changing Group Settings for Group In Jog

### ISSUE THREAD

**Issue by HunterACole** [ChicagoFlyhouse/AutomationConsole#10]
When a group in jog has it's settings changed, it's removed from the console jog window, but not the persistent axis table.

We would like to have the group stay in the jog window even when settings are changed

**Comment by code-warriors-llc** [comment]
We are working on the this point possibly we will upload fixed version on Monday for your testing.

**Comment by code-warriors-llc** [comment]
@HunterACole Done changes are on the Testconsle.
Please provide feedback after testing and close the issue if implementation meets with requirement
Thanks,

**Comment by HunterACole** [comment]
Tested as working on large console after changing settings in group, stayed in jog. Attempted to test on handheld but was unable to modify settings in group to confirm. See issue "Unable to Enter Data in Group SetUp" in AutomationConsole2020

**Comment by code-warriors-llc** [comment]
Yes we are working on it possibly tomorrow we will create a setup including this one. 
Thanks

**Comment by code-warriors-llc** [comment]
@HunterACole - Done Changes are uploaded on handheld device for testing

**Comment by HunterACole** [comment]
This issue is resolved on handhelds as well, see issue in AutomationConsole2020 for more handheld-specific bugs
