### ISSUE TITLE
Prevent user from changing locked group leader

### ISSUE THREAD

**Issue by HunterACole** [ChicagoFlyhouse/AutomationConsole#11]
As an operational improvement, please remove the ability to change leaders in an existing group. We want users to have to remove the group and recreate the group to assign the leader of their choice

**Comment by code-warriors-llc** [comment]
@HunterACole   Done changes are on the Testconsle. 
Please provide feedback after testing and close the issue if implementation meets with requirement 
Thanks,

**Comment by HunterACole** [comment]
Looks good on test console
