### ISSUE TITLE
Jog Axis on app start

### ISSUE THREAD

**Issue by HunterACole** [ChicagoFlyhouse/AutomationConsole#4]
The jog window being available on application launch is misleading, as attempting to use the jog function without a show open is impossible. Can we open a generic show on app startup to alleviate this? Is it possible for the jog function to be used without a show open?

**Comment by code-warriors-llc** [comment]
@HunterACole - We have enabled the jog function when the show is not opened. You can verify this on the test console.

**Comment by HunterACole** [comment]
Verified on test console when running from code, can include for next deployment

**Comment by code-warriors-llc** [comment]
Yes , we can include for next deployment.
